export const adminNavItems = [
  { href: "/admin/dashboard", label: "대시보드", section: "Overview", icon: "dashboard" },
  { href: "/admin/chatbots", label: "챗봇 관리", section: "Workspace", icon: "chatbot" },
  { href: "/admin/knowledge/register", label: "지식 등록", section: "Workspace", icon: "knowledge" },
  { href: "/admin/knowledge/list", label: "지식 목록", section: "Workspace", icon: "knowledge" },
  { href: "/admin/conversations", label: "대화 관리", section: "Workspace", icon: "conversation" },
  { href: "/admin/usage", label: "사용량", section: "Workspace", icon: "usage" },
  { href: "/admin/widget", label: "위젯 설정", section: "Workspace", icon: "widget" },
  { href: "/admin/ai/basic", label: "기본 AI", section: "AI Config", icon: "ai" },
  { href: "/admin/ai/style", label: "스타일 규칙", section: "AI Config", icon: "spark" },
  { href: "/admin/ai/conditional", label: "조건부 규칙", section: "AI Config", icon: "spark" },
  { href: "/admin/quality-report", label: "품질 리포트", section: "Operations", icon: "logs" },
  { href: "/admin/feedback", label: "피드백 현황", section: "Operations", icon: "logs" },
  { href: "/admin/knowledge-gap", label: "Knowledge Gap", section: "Operations", icon: "knowledge" },
  { href: "/admin/roi-dashboard", label: "ROI Dashboard", section: "Operations", icon: "usage" },
  { href: "/admin/billing", label: "결제 관리", section: "Operations", icon: "billing" },
  { href: "/admin/users", label: "사용자", section: "Operations", icon: "users" },
  { href: "/admin/security", label: "보안", section: "Operations", icon: "security" },
  { href: "/admin/notifications", label: "알림", section: "Operations", icon: "notification" },
  { href: "/admin/audit", label: "감사 로그", section: "Operations", icon: "logs" },
  { href: "/admin/install-guide", label: "설치 가이드", section: "Operations", icon: "widget" },
] as const;
