export const superAdminNavItems = [
  { href: "/super-admin/dashboard", label: "대시보드" },
  { href: "/super-admin/organizations", label: "조직 관리" },
  { href: "/super-admin/contracts", label: "계약 관리" },
  { href: "/super-admin/billing", label: "결제 관리" },
  { href: "/super-admin/accounts", label: "계정 관리" },
  { href: "/super-admin/api", label: "공용 API" },
  { href: "/super-admin/chatbots", label: "챗봇" },
  { href: "/super-admin/widgets", label: "위젯" },
  { href: "/super-admin/system", label: "시스템 제어" },
  { href: "/super-admin/notifications", label: "알림" },
  { href: "/super-admin/enforcement", label: "제재 관리" },
  { href: "/super-admin/api/usage", label: "API 사용량" },
  { href: "/super-admin/usage", label: "사용량 모니터링" },
  { href: "/super-admin/security", label: "보안 로그" },
] as const;
