export const superAdminNavItems = [
  { href: "/super-admin/dashboard", label: "대시보드", icon: "dashboard", section: "Overview" },
  { href: "/super-admin/organizations", label: "조직 관리", icon: "organization", section: "Tenant Ops" },
  { href: "/super-admin/contracts", label: "계약 관리", icon: "contract", section: "Tenant Ops" },
  { href: "/super-admin/billing", label: "결제 관리", icon: "billing", section: "Tenant Ops" },
  { href: "/super-admin/accounts", label: "계정 관리", icon: "account", section: "Tenant Ops" },
  { href: "/super-admin/blueprints", label: "Blueprint", icon: "chatbot", section: "Tenant Ops" },
  { href: "/super-admin/chatbots", label: "챗봇 관리", icon: "chatbot", section: "Service" },
  { href: "/super-admin/widgets", label: "위젯 관리", icon: "widget", section: "Service" },
  { href: "/super-admin/api", label: "API 설정", icon: "api", section: "Platform" },
  { href: "/super-admin/api/usage", label: "API 사용량", icon: "usage", section: "Platform" },
  { href: "/super-admin/answer-settings", label: "고급 답변 설정", icon: "system", section: "Platform" },
  { href: "/super-admin/system", label: "시스템 제어", icon: "system", section: "Platform" },
  { href: "/super-admin/notifications", label: "알림", icon: "notification", section: "Platform" },
  { href: "/super-admin/enforcement", label: "제재 관리", icon: "security", section: "Platform" },
  { href: "/super-admin/usage", label: "사용량 모니터링", icon: "usage", section: "Audit" },
  { href: "/super-admin/security", label: "보안 로그", icon: "logs", section: "Audit" },
] as const;
