"""add_answer_evaluations

Revision ID: 24d3cb059840
Revises: 20260803_0049
Create Date: 2026-08-09 01:20:45.681937
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '24d3cb059840'
down_revision: Union[str, None] = '20260803_0049'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('answer_evaluations',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('chatbot_id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('relevance_score', sa.SmallInteger(), nullable=True),
    sa.Column('groundedness_score', sa.SmallInteger(), nullable=True),
    sa.Column('context_score', sa.SmallInteger(), nullable=True),
    sa.Column('followup_score', sa.SmallInteger(), nullable=True),
    sa.Column('topic_drift', sa.Boolean(), nullable=False),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.Column('verdict_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('method', sa.String(length=20), nullable=False),
    sa.Column('evaluator_model', sa.String(length=120), nullable=True),
    sa.Column('prompt_version', sa.String(length=20), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chatbot_id'], ['chatbot_settings.id'], name=op.f('fk_answer_evaluations_chatbot_id_chatbot_settings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['chat_messages.id'], name=op.f('fk_answer_evaluations_message_id_chat_messages'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_answer_evaluations_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_answer_evaluations')),
    sa.UniqueConstraint('message_id', name='uq_answer_evaluations_message')
    )
    op.create_index('ix_answer_evaluations_chatbot_time', 'answer_evaluations', ['chatbot_id', 'evaluated_at'], unique=False)
    op.create_index('ix_answer_evaluations_review', 'answer_evaluations', ['chatbot_id', 'needs_review'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_answer_evaluations_review', table_name='answer_evaluations')
    op.drop_index('ix_answer_evaluations_chatbot_time', table_name='answer_evaluations')
    op.drop_table('answer_evaluations')
    # ### end Alembic commands ###
